<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NEWSPAPER [ 

<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT LEAD (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)> 

<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>

<!ENTITY NEWSPAPER "Vervet Logic Times">
<!ENTITY PUBLISHER "Vervet Logic Press">
<!ENTITY COPYRIGHT "Copyright 2016 Vervet Logic Press">

]>
<NEWSPAPER>
	<ARTICLE AUTHOR="张三">
		<HEADLINE>哈哈哈</HEADLINE>
		<BYLINE>啊啊啊啊啊</BYLINE>
		<LEAD>啦啦啦</LEAD>
		<BODY>嘿嘿嘿嘿</BODY>
		<NOTES>&COPYRIGHT;</NOTES>
	</ARTICLE>




</NEWSPAPER>
